spring:  
  datasource:
    url: jdbc:mysql://localhost:3306/jzy_cxkj
    username: root  
    password: 1234  
    driver-class-name: com.mysql.jdbc.Driver
    max-idle: 10
    max-wait: 10000
    min-idle: 5
    initial-size: 5
  cloud:
    refresh:
      refreshable: none
mybatis:
  mapper-locations: classpath*:com/ly/*/mapper/*.xml
name: foo-dev6899